include ../Makefile.tests_common

USEMODULE += embunit
USEMODULE += udp_client
USEMODULE += udp_server

USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6_router_default
USEMODULE += gnrc_pktdump
USEMODULE += netstats_ipv6

include $(RIOTBASE)/Makefile.include
