USEMODULE += random
USEMODULE += ipv6_addr
USEMODULE += netdev_default
USEMODULE += gnrc_ipv6_default
USEMODULE += auto_init_gnrc_netif

ifneq (,$(filter m4a-24g m4a-mb,$(BOARD)))
    USEMODULE += radio
else
    USEMODULE += periph_hwrng
endif
