---
kind: pipeline
type: docker

steps:
  - name: build-m4a-24g
    image: luisan00/m4abuild-base:latest
    commands:
      - git submodule update --init --recursive
      - make -C firmware BOARD=m4a-24g

trigger:
  event:
    - push
    - pull_request
