---
kind: pipeline
type: docker

steps:
  - name: build
    image: luisan00/m4abuild-base:dev
    commands:
      - git submodule update --init --recursive
      - cd wifi-subsys && idf.py build

trigger:
  event:
    - push
    - pull_request
