---
kind: pipeline
type: docker

steps:
  - name: build
    image: espressif/idf:release-v4.3
    commands:
      - git submodule update --init --recursive
      - cd wifi-subsys && idf.py build

trigger:
  event:
    - push
    - pull_request
