---
kind: pipeline
type: docker

steps:
  - name: clone-project
    image: ubuntu:latest
    commands:
      - git submodule update --init --recursive

trigger:
  event:
    - push
    - pull_request
