USEMODULE += radio
USEMODULE += gnrc_rpl
USEMODULE += auto_init_gnrc_rpl
USEMODULE += gnrc_ipv6_router_default

ifneq (,$(filter 6lpan_node,$(USEMODULE)))
     USEMODULE += gnrc_sixlowpan_router_default
endif
