APPLICATION ?= tests_$(notdir $(patsubst %/,%,$(CURDIR)))

ifneq (,$(wildcard $(CURDIR)/tests*/.))
  DEFAULT_MODULE += test_utils_interactive_sync
  # add stack metric printing configuration when testing Kconfig
  # add interactive test configuration when testing Kconfig
  ifeq (1,$(TEST_KCONFIG))
    KCONFIG_ADD_CONFIG += $(RIOTBASE)/tests/test_utils.config
    KCONFIG_ADD_CONFIG += $(RIOTBASE)/tests/test_interactive.config
  endif
endif

ifneq (,$(filter tests_driver_%,$(APPLICATION)))
  BOARD ?= m4a-24g
endif

APPBASE ?= $(CURDIR)
BOARD ?= m4a-24g
MESHBASE ?= $(RIOTBASE)/..
QUIET ?= 1
RIOTBASE ?= $(CURDIR)/../../RIOT
EXTERNAL_BOARD_DIRS ?= $(CURDIR)/../../boards
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../firmware/peripherals
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../firmware/network
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../firmware/sys
CFLAGS += -I $(CURDIR)/../../firmware

SLIP_UART ?= 1
CFLAGS += "-DSLIPDEV_PARAM_UART=UART_DEV($(SLIP_UART))"


# DEVELHELP enabled by default for all tests, set 0 to disable
DEVELHELP ?= 1

-include $(MESHBASE)/makefiles/tools/firmupdater.mk
