APPLICATION = moisture_sensor_test

include ../Makefile.common

FEATURES_REQUIRED = periph_adc
USEMODULE += ztimer
USEMODULE += ztimer_msec

DEVHELP ?= 1
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
