ifneq (,$(filter uniqueid,$(USEMODULE)))
    DIRS += uniqueid
endif

ifneq (,$(filter udp_server,$(USEMODULE)))
    DIRS += udp_server
endif

ifneq (,$(filter udp_client,$(USEMODULE)))
    DIRS += udp_client
endif

include $(RIOTBASE)/Makefile.base
