include ../Makefile.tests_common

FEATURES_REQUIRED = periph_i2c
FEATURES_OPTIONAL = periph_i2c_reconfigure

USEMODULE += ztimer
USEMODULE += ztimer_msec
USEMODULE += i2c_scan
USEMODULE += embunit

include $(RIOTBASE)/Makefile.include