include ../Makefile.tests_common
# Required/Optional features
FEATURES_REQUIRED = periph_i2c
FEATURES_OPTIONAL = periph_i2c_reconfigure
# Required modules
USEMODULE += i2c_scan
USEMODULE += embunit

include $(RIOTBASE)/Makefile.include
