APPLICATION ?= shell_extended

include ../Makefile.common

# Include the shell extended module, shell and shell commands modules
# will be implicitly included.
USEMODULE += shell_extended

# Include desired modules where shell extended is enabled.
USEMODULE += uniqueid
USEMODULE += net_tools

include $(RIOTBASE)/Makefile.include
