APPLICATION ?= shell_extended

include ../Makefile.common
# include desired modules:
USEMODULE += radio
# include the shell:
USEMODULE += shell_extended
USEMODULE += xtimer

include $(RIOTBASE)/Makefile.include
