ifneq (,$(filter at_client,$(USEMODULE)))
  DIRS += at_client
endif

ifneq (,$(filter serialization,$(USEMODULE)))
  DIRS += serialization
endif

ifneq (,$(filter storage,$(USEMODULE)))
  DIRS += storage
endif

ifneq (,$(filter uniqueid,$(USEMODULE)))
  DIRS += uniqueid
endif

include $(RIOTBASE)/Makefile.base
