ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
    USEMODULE += gnrc_netdev_default
endif

ifeq (,$(filter gnrc_sixlowpan_router_default,$(USEMODULE)))
    USEMODULE +=  gnrc_sixlowpan_router_default
endif

ifneq (,$(filter gnrc_udp,$(USEMODULE)))
    USEMODULE += gnrc_udp
endif
ifneq (,$(filter gnrc_icmpv6_echo,$(USEMODULE)))
    USEMODULE += gnrc_icmpv6_echo
endif

ifeq (,$(filter auto_init_gnrc_netif,$(USEMODULE)))
    USEMODULE +=  auto_init_gnrc_netif
endif

ifeq (,$(filter rpl_protocol,$(USEMODULE)))
    USEMODULE +=  rpl_protocol
endif
