ifeq (,$(filter usbus_cdc_ecm,$(USEMODULE)))
    USEMODULE +=  usbus_cdc_ecm
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
    USEMODULE += netdev_default
endif

ifneq (,$(filter auto_init_usbus,$(USEMODULE)))
    USEMODULE +=  auto_init_usbus
endif

ifeq (,$(filter auto_init_gnrc_netif,$(USEMODULE)))
    USEMODULE +=  auto_init_gnrc_netif
endif

ifneq (,$(filter gnrc_icmpv6_error,$(USEMODULE)))
    USEMODULE +=  gnrc_icmpv6_error
endif

ifeq (,$(filter gnrc_sixlowpan_border_router_default,$(USEMODULE)))
    USEMODULE +=  gnrc_sixlowpan_border_router_default
endif

ifneq (,$(filter gnrc_udp,$(USEMODULE)))
    USEMODULE += gnrc_udp
endif

ifneq (,$(filter gnrc_icmpv6_echo,$(USEMODULE)))
    USEMODULE += gnrc_icmpv6_echo
endif

ifneq (,$(filter gnrc_ipv6_default,$(USEMODULE)))
    USEMODULE += gnrc_ipv6_default
endif

ifneq (,$(filter gnrc_netif_ieee802154,$(USEMODULE)))
    USEMODULE += gnrc_netif_ieee802154
endif

ifeq (,$(filter rpl_protocol,$(USEMODULE)))
    USEMODULE +=  rpl_protocol
endif
