include ../Makefile.tests_common

USEMODULE += embunit
USEMODULE += storage

# USEMODULE += radio
# USEMODULE += rpl_protocol

# ifneq (,$(filter m4a-24g,$(BOARD)))
#      USEMODULE += stdio_cdc_acm
# endif

include $(RIOTBASE)/Makefile.include
