name: Codespell

on: [push, pull_request]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
            check_filenames: false
            skip: RIOT, .git
            ignore_words_file: dist/tools/codespell/ignored_words.txt
